# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/04-Settings

prod:
  .settings:
    no_script_name:         false
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    # Form security secret (CSRF protection)
    csrf_secret:            f546155df2f892b337bd9d5b216f1730080c6209

    # Output escaping settings
    escaping_strategy:      true
    escaping_method:        ESC_SPECIALCHARS

    # Enable the database manager
    use_database:           true
    
    # ::NUEVO:: Como los plugins son compartidos entre todas las aplicaciones 
    # de un proyecto, tienes que permitir explícitamente los módulos que deseas
    # utilizar agregando el item enabled_modules.
    enabled_modules: [default, sfGuardAuth, sfGuardUser]
    
  # ::NUEVO:: Para cambiar la accion por defecto empleada por la pagina del login
  .actions:
    login_module:    sfGuardAuth
    login_action:    signin