<?php

/**
 * Categoria
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PROYECTO_PRUEBA
 * @subpackage model
 * @author     ROSMAN_TORRES
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Categoria extends BaseCategoria
{
  public function __toString()
  {
    return $this->getNombre();
  }
}