<?php

/**
 * CategoriaAfiliadoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoriaAfiliadoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoriaAfiliadoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CategoriaAfiliado');
    }
}