<?php

/**
 * Trabajo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    PROYECTO_PRUEBA
 * @subpackage model
 * @author     ROSMAN_TORRES
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Trabajo extends BaseTrabajo {

  /*
   * "Slugeando" valores de columnas mediante la sustitución de todos los 
   * caracteres no ASCII por un -. 
   */
  public function getCompaniaSlug()
  {
    return Jobeet::slugear($this->getCompania());
  }

  public function getPosicionSlug()
  {
    return Jobeet::slugear($this->getPosicion());
  }

  public function getLocalizacionSlug()
  {
    return Jobeet::slugear($this->getLocalizacion());
  }

}