<?php

/**
 * TrabajoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TrabajoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TrabajoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Trabajo');
    }
}